-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.email_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  email text NOT NULL,
  otp text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_otps_pkey PRIMARY KEY (id),
  CONSTRAINT email_otps_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.match_suggestions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ride_template_id uuid NOT NULL,
  ride_request_id uuid NOT NULL,
  route_match_score numeric DEFAULT 0,
  schedule_match_score numeric DEFAULT 0,
  overall_score numeric DEFAULT 0,
  detour_distance_meters integer,
  detour_time_seconds integer,
  pickup_distance_meters integer,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'shown'::text, 'accepted'::text, 'skipped'::text, 'expired'::text, 'confirmed'::text])),
  shown_to_host_at timestamp with time zone,
  host_action_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  CONSTRAINT match_suggestions_pkey PRIMARY KEY (id),
  CONSTRAINT match_suggestions_ride_template_id_fkey FOREIGN KEY (ride_template_id) REFERENCES public.ride_templates(id),
  CONSTRAINT match_suggestions_ride_request_id_fkey FOREIGN KEY (ride_request_id) REFERENCES public.ride_requests(id)
);
CREATE TABLE public.pod_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pod_id uuid NOT NULL,
  rider_id uuid NOT NULL,
  ride_request_id uuid,
  pickup_location text NOT NULL,
  pickup_lat double precision NOT NULL,
  pickup_lng double precision NOT NULL,
  pickup_point USER-DEFINED,
  host_approved_at timestamp with time zone,
  rider_confirmed_at timestamp with time zone,
  status text DEFAULT 'pending_host'::text CHECK (status = ANY (ARRAY['pending_host'::text, 'pending_rider'::text, 'active'::text, 'removed'::text, 'left'::text])),
  joined_at timestamp with time zone,
  left_at timestamp with time zone,
  CONSTRAINT pod_members_pkey PRIMARY KEY (id),
  CONSTRAINT pod_members_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id),
  CONSTRAINT pod_members_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.profiles(id),
  CONSTRAINT pod_members_ride_request_id_fkey FOREIGN KEY (ride_request_id) REFERENCES public.ride_requests(id)
);
CREATE TABLE public.pods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ride_template_id uuid NOT NULL,
  host_id uuid NOT NULL,
  name text,
  days_active ARRAY NOT NULL DEFAULT '{}'::text[],
  departure_time time without time zone NOT NULL,
  origin_location text NOT NULL,
  destination_location text NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'dissolved'::text])),
  created_at timestamp with time zone DEFAULT now(),
  dissolved_at timestamp with time zone,
  CONSTRAINT pods_pkey PRIMARY KEY (id),
  CONSTRAINT pods_ride_template_id_fkey FOREIGN KEY (ride_template_id) REFERENCES public.ride_templates(id),
  CONSTRAINT pods_host_id_fkey FOREIGN KEY (host_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL,
  age integer,
  gender text,
  institution text,
  from_location text,
  to_location text,
  leave_home_time time without time zone,
  leave_college_time time without time zone,
  days_of_commute ARRAY,
  prefer_hosting boolean DEFAULT false,
  prefer_taking_ride boolean DEFAULT false,
  vehicle_type text,
  comfortable_with text,
  agreed_to_terms boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  phone_number text,
  otp_verified boolean DEFAULT false,
  institutional_email text,
  email_verified boolean DEFAULT false,
  from_lat double precision,
  from_lng double precision,
  to_lat double precision,
  to_lng double precision,
  home_location USER-DEFINED,
  college_location USER-DEFINED,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.ride_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rider_id uuid NOT NULL,
  pickup_location text NOT NULL,
  pickup_lat double precision NOT NULL,
  pickup_lng double precision NOT NULL,
  pickup_point USER-DEFINED,
  destination_location text NOT NULL,
  destination_lat double precision NOT NULL,
  destination_lng double precision NOT NULL,
  destination_point USER-DEFINED,
  preferred_arrival_time time without time zone NOT NULL,
  time_flexibility_mins integer DEFAULT 15 CHECK (time_flexibility_mins >= 0),
  days_needed ARRAY NOT NULL DEFAULT '{}'::text[],
  vehicle_preference text DEFAULT 'any'::text CHECK (vehicle_preference = ANY (ARRAY['2_wheeler'::text, '4_wheeler'::text, 'any'::text])),
  gender_preference text DEFAULT 'both'::text CHECK (gender_preference = ANY (ARRAY['male'::text, 'female'::text, 'both'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'matched'::text, 'archived'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ride_requests_pkey PRIMARY KEY (id),
  CONSTRAINT ride_requests_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ride_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  host_id uuid NOT NULL,
  from_location text NOT NULL,
  from_lat double precision NOT NULL,
  from_lng double precision NOT NULL,
  from_point USER-DEFINED,
  to_location text NOT NULL,
  to_lat double precision NOT NULL,
  to_lng double precision NOT NULL,
  to_point USER-DEFINED,
  departure_time time without time zone NOT NULL,
  return_time time without time zone,
  days_available ARRAY NOT NULL DEFAULT '{}'::text[],
  vehicle_type text NOT NULL CHECK (vehicle_type = ANY (ARRAY['2_wheeler'::text, '4_wheeler'::text])),
  available_seats integer NOT NULL DEFAULT 1 CHECK (available_seats >= 1),
  seats_taken integer NOT NULL DEFAULT 0 CHECK (seats_taken >= 0),
  gender_preference text DEFAULT 'both'::text CHECK (gender_preference = ANY (ARRAY['male'::text, 'female'::text, 'both'::text])),
  max_detour_meters integer DEFAULT 2000,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'archived'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ride_templates_pkey PRIMARY KEY (id),
  CONSTRAINT ride_templates_host_id_fkey FOREIGN KEY (host_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);